### ISSUE TITLE
Generated swagger.yml file always includes a `200` response since Micronaut 2.2.0

### ISSUE THREAD

**Issue by sk8geek** [micronaut-projects/micronaut-openapi#494]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to GitLab
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Get the latest version of Micronaut and include the OpenAPI feature.
2. Create a `@Controller` with a `@Put` operation and annotate with `@ApiResponse(responseCode = "204")`
3. Build the project
4. Note that the generated swagger yml file includes a `200` response for the endpoint

### Expected Behaviour

The generated swagger yml file should only include the annotated responses.

### Actual Behaviour

The generated file always includes a `200` response.

### Environment Information

- **Operating System**: Fedora Core 33
- **Micronaut Version:** This seems to be broken from 2.2.0 onwards. In 2.1.4 the file is correctly generated.
- **JDK Version:** 11.0.7

### Example Application

An example project: https://gitlab.com/sk8geek/test-swagger

**Comment by dstepanov** [comment]
What is the actual response code by Micronaut? You might need to use `@Status`

**Comment by sk8geek** [comment]
Thanks @dstepanov , when I run the application and call the endpoint I get the correct (`204`) response.  
I've never used `@Status` before but this does fix this issue, thank you.  This feels like a change in default behaviour that has been silently introduced.
